version: 2.1

jobs:
  test-app:
    #working_directory: ~/circleci-python
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install all required dependencies
          command: |
            apt-get update -y
            apt-get install curl -y
            apt-get install python3 -y
            apt install python3-pip -y
            pip3 install --upgrade pip
            pip3 install flask
            pip3 install flask-mysql
            python3 app.py &


workflows:
  build_and_test:
    jobs:
      - test-app
      