version: 2.1

jobs:
  test-app:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install all required dependencies
          command: |
            apt-get update -y
            apt-get install curl -y
            apt-get install python3 -y
            apt install python3-pip -y
            pip3 install --upgrade pip
            pip3 install flask
            pip3 install flask-mysql
            python3 app.py &        
  build-docker:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      #- setup_remote_docker:
      #  version: 19.03.12
      - run:
        name: test
        command: |
          echo "Hello World"

workflows:
  build_and_test:
    jobs:
      - test-app
      - build-docker
      #  requires: [test-app]
      