version: 2.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install all required dependencies
          command: |
            apt-get update -y
            apt-get install python3 -y
            apt install python3-pip -y
            pip3 install --upgrade pip -y
            pip3 install flask -y
            pip3 install flask-mysql -y
            python3 app.py


workflows:
  build_and_test:
    jobs:
      - build
      