version: 2.1

jobs:
  test-app:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Run the server
          command: |
            apt-get update -y
            apt-get install curl -y
            apt-get install python3 -y
            apt install python3-pip -y
            pip3 install --upgrade pip
            pip3 install flask
            pip3 install flask-mysql
            python3 app.py & 
  docker-build:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
        name: test
        command: |
          echo "hello world"      

workflows:
  build_and_test:
    jobs:
      - test-app
      - docker-build
      