version: 2.1

jobs:
  build-app:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 app.py
#  test:

  build-image:
      docker:
        - image: docker:19.03.12
      steps:
        - checkout
        - setup_remote_docker
        - run:
          name: build docker image
          command: |
            docker build -f Dockerfile -t abdelrahmangaber/simple-webapp-flask
            docker push abdelrahmangaber/simple-webapp-flask
  #deploy-ec2:
  #configure-ec2:
  #deploy-container:


Workflows:
  default:
    jobs:
      - build-app
      #test:
      # requires: [build-app]
      build_image:
        requires: [build-app]
      #deploy-ec2:
      #  requires: []
      #configure-ec2:
      #  requires: []
      #deploy-container:
      #  requires: []
      
      