version: 2.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "centos"
    steps:
      - checkout
      - run:
          name: Install all required dependencies
          command: |
            yum update
            yum install python3
            pip install --upgrade pip
            pip install flask
            pip install flask-mysql
            python3 app.py


workflows:
  build_and_test:
    jobs:
      - build
      