version: 2.1

jobs:
  test-app:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install all required dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install curl -y
            sudo apt-get install python3 -y
            sudo apt install python3-pip -y
            sudo pip3 install --upgrade pip
            sudo pip3 install flask
            sudo pip3 install flask-mysql
            python3 app.py &
  #build-docker:
  #  docker:
  #    - image: "docker:19.03.12"
  #  steps:
  #    - checkout
  #    - setup_remote_docker
   #    - run:
   #     name: run docker conatiner
   #     command: | 
   #       docker run -d -p 80:80 --name my-apache-container httpd

workflows:
  build_and_test:
    jobs:
      - test-app
      #- build-docker:
      #  requires: [test-app]
      