version: 2.1

jobs:
  test-app:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt-get install curl -y
            apt-get install python3 -y
            apt install python3-pip -y
            pip3 install --upgrade pip
            pip3 install flask
            pip3 install flask-mysql
      - run:
          name: run the app
          command: |
            python3 app.py & 
  docker-build:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo "Hello World!"

workflows:
  build_and_test:
    jobs:
      - test-app
      